"""empty message

Revision ID: cbe89e18a65d
Revises: 573d726a5860
Create Date: 2017-10-19 10:11:16.624446

"""
import sqlalchemy as sa
from alembic import op

import octoprint_dashboard

# revision identifiers, used by Alembic.

revision = 'cbe89e18a65d'
down_revision = '573d726a5860'
branch_labels = None
depends_on = None

OAUTH_CVUT = "oauth_cvut"
NONE = "none"

AUTH_CHOICES = (
    (OAUTH_CVUT, "ČVUT - OAuth"),
    (NONE, "None")
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config',
                  sa.Column('auth', octoprint_dashboard.model.utils.ChoiceType(AUTH_CHOICES), server_default=NONE,
                            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'auth')
    # ### end Alembic commands ###
